#!/bin/bash
wget https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz -o geckodriver.tar.gz
tar -xf geckodriver.tar.gz
mv geckodriver /usr/bin/
rm geckodriver.tar.gz