version: '3'


services:
        webfrontend:
                build: ./src/nginx/.
                restart: always
        flask:
                build: ./src/flask/.
                restart: always
                links:
                        - webfrontend
                        - selenium
                          # - "carbon"
        #carbon:
        #        build: ./src/carbon/.
        #        restart: always
        selenium:
                build: ./src/selenium/.
                restart: always
                expose:
                  - 4444
                  - 7900

